export const lightTheme = {
  backgroundColor: "#ffffff",
  primaryColor: "#2ecc71",
  secondaryColor: "red",
  textColor: "#333333",
  buttonBackground: "#222222",
  buttonText: "#f5f5f5",
  grayText: "gray",
  tabIconColor: "#333333",
  innerTabContainerColor: "rgba(0, 0, 0, 0.06)",
  chatListBackgroundColor: "#f3f4f6",
  chatBackgroundImage: require("../../assets/chat_background.jpg"),
  chatContactColor: "#ffffff",
  archiveBackgroundColor: "#ffffff",
  archiveTextColor: "#2F3E46",
};

export const darkTheme = {
  backgroundColor: "#000000",
  primaryColor: "#2ecc71",
  secondaryColor: "red",
  textColor: "#f5f5f5",
  buttonBackground: "#f8f8f8",
  buttonText: "#f5f5f5",
  grayText: "gray",
  tabIconColor: "#f5f5f5",
  innerTabContainerColor: "rgba(255, 255, 255, 0.2)",
  chatListBackgroundColor: "#000000",
  chatBackgroundImage: require("../../assets/chat_background_dark_1.jpg"),
  chatContactColor: "red",
  archiveBackgroundColor: "#2F3E46",
  archiveTextColor: "#ffffff",
};
